# Generated by Django 3.2.7 on 2022-04-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwttokenmodel',
            name='expiry_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
